const CURRENT_KEY='bs.batteries.current.v1',HISTORY_KEY='bs.batteries.history.v1',LEGACY_KEY='bs.batteries.state',ZOOM_KEY='bs.batteries.historyZoom.v2';
const SAMPLE_MS=30000,SAVE_MS=2000,MAX_AGE=840*86400000,BARS=30;
const ZOOMS=[['5 min',5*60000],['15 min',15*60000],['1 h',3600000],['3 h',3*3600000],['6 h',6*3600000],['12 h',12*3600000],['1 día',86400000],['7 días',7*86400000],['28 días',28*86400000]];
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const clone=v=>{try{return JSON.parse(JSON.stringify(v))}catch{return v}};

function migrate(){if(read(CURRENT_KEY,null))return;const old=read(LEGACY_KEY,null);if(!old||typeof old!=='object')return;write(CURRENT_KEY,{bankName:old.bankName||'Banco principal',batteries:Array.isArray(old.batteries)?old.batteries:[]});if(Array.isArray(old.history)&&old.history.length)write(HISTORY_KEY,old.history)}

export function createBatteriesModule(requestRender,openManager){
  migrate();
  const saved=read(CURRENT_KEY,{}),state={bankName:String(saved.bankName||'Banco principal'),batteries:Array.isArray(saved.batteries)?saved.batteries:[],history:Array.isArray(read(HISTORY_KEY,[]))?read(HISTORY_KEY,[]):[],remoteAuthoritative:false,remoteStats:null,root:null,lastSample:0};
  let saveTimer=0,historyDirty=false,zoom=Math.max(0,Math.min(ZOOMS.length-1,Number(read(ZOOM_KEY,0))||0)),drawPending=false;
  const saveCurrent=(immediate=false)=>{const save=()=>{saveTimer=0;write(CURRENT_KEY,{bankName:state.bankName,batteries:state.batteries})};if(immediate){clearTimeout(saveTimer);save()}else if(!saveTimer)saveTimer=setTimeout(save,SAVE_MS)};
  function compactHistory(){const now=Date.now(),bins=new Map();for(const p of state.history.filter(p=>Number(p?.time)>=now-MAX_AGE&&num(p?.soc)!==null)){const age=now-Number(p.time),unit=age>365*86400000?7*86400000:age>90*86400000?86400000:age>30*86400000?21600000:age>7*86400000?7200000:age>48*3600000?1800000:age>6*3600000?300000:30000,key=Math.floor(Number(p.time)/unit)*unit;let b=bins.get(key);if(!b){b={time:Number(p.time),n:0,soc:0,current:0,currentN:0,voltage:0,voltageN:0,parts:new Map()};bins.set(key,b)}b.n++;b.soc+=Number(p.soc);const c=num(p.current),v=num(p.voltage);if(c!==null){b.current+=c;b.currentN++}if(v!==null){b.voltage+=v;b.voltageN++}b.time=Math.max(b.time,Number(p.time));for(const part of p.batteries||[]){const q=num(part?.contribution);if(q===null)continue;const id=String(part.id||part.name||'battery'),x=b.parts.get(id)||{id,name:String(part.name||'Batería'),sum:0,n:0};x.sum+=q;x.n++;b.parts.set(id,x)}}state.history=[...bins.values()].map(b=>({time:b.time,soc:b.soc/b.n,current:b.currentN?b.current/b.currentN:null,voltage:b.voltageN?b.voltage/b.voltageN:null,batteries:[...b.parts.values()].map(x=>({id:x.id,name:x.name,contribution:x.sum/x.n}))})).sort((a,b)=>a.time-b.time)}
  function saveHistory(){if(!historyDirty)return;historyDirty=false;compactHistory();write(HISTORY_KEY,state.history)}
  window.addEventListener('pagehide',()=>{saveCurrent(true);saveHistory()});
  function stats(){let cap=0,rem=0,current=0,vs=0,vn=0,connected=0;for(const b of state.batteries){const c=num(b.capacityAh)||0,s=num(b.soc),r=num(b.remainingAh),a=num(b.current),v=num(b.voltage);cap+=c;rem+=r!==null?r:(s!==null?s*c/100:0);if(a!==null)current+=a;if(v!==null){vs+=v;vn++;if(b.connected!==false)connected++}}const voltage=vn?vs/vn:null,soc=cap?Math.max(0,Math.min(100,rem/cap*100)):null;return{cap,rem,current,voltage,soc,power:voltage===null?null:voltage*current,connected,total:state.batteries.length}}
  const summary=()=>{const s=stats();return s.soc===null?(s.cap?`${Math.round(s.cap)} Ah`:'Sin datos'):`${Math.round(s.soc)}% · ${Math.round(s.rem)}/${Math.round(s.cap)} Ah`};
  const metric=(v,l)=>`<div class="metric"><div class="value">${v}</div><div class="label">${l}</div></div>`;
  function mini(b,i){const soc=num(b.soc),v=num(b.voltage),a=num(b.current),cap=num(b.capacityAh)||0,rem=num(b.remainingAh),shown=rem!==null?rem:(soc!==null?soc*cap/100:null),online=b.connected!==false&&v!==null;return `<div class="battery-mini ${online?'online':'offline'}"><div class="battery-mini-head"><strong>${esc(b.name||b.deviceName||`Batería ${i+1}`)}</strong><span class="battery-mini-link">${online?'⌁':'×'}</span></div><div class="battery-mini-body"><div class="battery-mini-ring" style="--soc:${soc??0}"><span>${soc===null?'—':Math.round(soc)+'%'}</span></div><div class="battery-mini-right"><div class="battery-mini-top"><div><b>${v===null?'—':v.toFixed(2)+' V'}</b><small>Voltaje</small></div><div><b>${a===null?'—':(a>=0?'+':'')+a.toFixed(1)+' A'}</b><small>Corriente</small></div></div><div class="battery-mini-charge"><span>${shown===null?'—':`${Math.round(shown)} / ${Math.round(cap)} Ah`}</span><small>Carga</small></div></div></div></div>`}
  function overview(){const s=stats(),minis=state.batteries.length?state.batteries.map(mini).join(''):'<div class="battery-mini-empty">Sin baterías vinculadas</div>';return `<div class="battery-overview"><div class="battery-bank-panel"><div class="battery-hero"><div class="battery-ring" style="--soc:${s.soc??0}"><div><strong>${s.soc===null?'—':Math.round(s.soc)+'%'}</strong><span>Carga</span></div></div><div class="battery-bank-name">${esc(state.bankName)}</div><div class="battery-ah">${Math.round(s.rem)} / ${Math.round(s.cap)} Ah</div></div><div class="metric-grid three compact-bank-metrics">${metric(s.voltage===null?'—':s.voltage.toFixed(2)+' V','Voltaje')}${metric(s.current.toFixed(1)+' A','Corriente')}${metric(s.power===null?'—':Math.round(s.power)+' W','Potencia')}</div><div class="battery-connected">${s.connected} de ${s.total} baterías conectadas</div></div><div class="battery-mini-column">${minis}</div></div>`}
  function historyPage(){const [label,ms]=ZOOMS[zoom],total=ms*BARS,span=total>=86400000?`${Math.round(total/86400000)} días`:`${Math.round(total/3600000)} h`;return `<div class="battery-history-page"><div class="battery-history-head"><div><strong>Histórico de carga</strong><small>30 barras · ${label} por barra · ${span}</small></div><div class="battery-history-zoom"><button type="button" data-battery-history-zoom="out" ${zoom===0?'disabled':''}>−</button><b>${label}</b><button type="button" data-battery-history-zoom="in" ${zoom===ZOOMS.length-1?'disabled':''}>+</button></div></div><div class="battery-history-chart"><div class="battery-history-y"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><canvas data-battery-history-chart></canvas></div><div class="battery-history-legend" data-battery-history-legend></div><small class="battery-history-foot">Verde: carga · rojo: descarga · cada segmento representa el aporte porcentual de una batería.</small></div>`}
  function statPage(){const s=stats();return `<div class="battery-list battery-stats-list">${row('Carga actual',s.soc===null?'—':Math.round(s.soc)+'%',`${Math.round(s.rem)} / ${Math.round(s.cap)} Ah`)}${row('Baterías conectadas',`${s.connected} de ${s.total}`,'Datos recibidos por Bluetooth')}${row('Potencia actual',s.power===null?'—':Math.round(s.power)+' W',s.current>=0?'Cargando':'Descargando')}</div>`}
  const row=(name,value,detail)=>`<div class="battery-item"><div class="battery-item-top"><span class="battery-name">${name}</span><span class="battery-soc">${value}</span></div><div class="battery-item-sub"><span>${detail}</span></div></div>`;
  function listPage(){if(!state.batteries.length)return `<div class="battery-empty"><div>No hay baterías vinculadas</div><button class="gps-action primary" type="button" data-battery-manage>Administrar Banco de Baterías</button></div>`;return `<div class="battery-list">${state.batteries.map(b=>row(esc(b.name||b.deviceName||'Batería'),num(b.soc)===null?'—':Math.round(num(b.soc))+'%',`${num(b.capacityAh)||0} Ah · ${b.connected===false?'Offline':'Conectada'}`)).join('')}</div>`}
  const page=i=>i===0?overview():i===1?historyPage():i===2?statPage():listPage();
  function partsSnapshot(){const cap=state.batteries.reduce((n,b)=>n+(num(b.capacityAh)||0),0);if(!cap)return[];return state.batteries.map((b,i)=>{const c=num(b.capacityAh)||0,rem=num(b.remainingAh),soc=num(b.soc),value=rem!==null?rem/cap*100:(soc===null?0:soc*c/cap);return{id:String(b.id||b.address||i),name:String(b.name||b.deviceName||`Batería ${i+1}`),contribution:Math.max(0,Math.min(100,value))}}).filter(b=>b.contribution>0)}
  function appendHistory(s){const now=Date.now();if(now-state.lastSample<SAMPLE_MS)return;state.lastSample=now;state.history.push({time:now,soc:s.soc,current:s.current,voltage:s.voltage,batteries:partsSnapshot()});historyDirty=true;saveHistory()}
  function chartData(){const [_,ms]=ZOOMS[zoom],end=Math.floor(Date.now()/ms)*ms+ms,start=end-ms*BARS,bars=Array.from({length:BARS},()=>({parts:new Map(),current:0,currentN:0,soc:null}));for(const p of state.history){const i=Math.floor((Number(p?.time)-start)/ms);if(i<0||i>=BARS)continue;const b=bars[i],c=num(p.current);if(c!==null){b.current+=c;b.currentN++}b.soc=num(p.soc);for(const part of p.batteries||[]){const v=num(part?.contribution);if(v===null)continue;const id=String(part.id||part.name||'battery'),x=b.parts.get(id)||{id,name:String(part.name||'Batería'),sum:0,n:0};x.sum+=v;x.n++;b.parts.set(id,x)}}return bars.map(b=>({parts:[...b.parts.values()].map(x=>({...x,value:x.sum/x.n})),current:b.currentN?b.current/b.currentN:null,soc:b.soc}))}
  function draw(root){const active=window.BoatStationPageLayout?.currentPage?.(root),canvas=root?.querySelector(`.page[data-page="${active}"] [data-battery-history-chart]`);if(!canvas)return;const r=canvas.getBoundingClientRect();if(r.width<10||r.height<10)return;const dpr=devicePixelRatio||1,w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;const c=canvas.getContext('2d'),bars=chartData(),slot=r.width/BARS,bw=Math.max(2,slot*.72),legend=new Map();c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,r.width,r.height);c.strokeStyle='#28516a';for(let i=0;i<=4;i++){const y=Math.round(i*r.height/4)+.5;c.beginPath();c.moveTo(0,y);c.lineTo(r.width,y);c.stroke()}bars.forEach((b,i)=>{if(!b.parts.length)return;const charging=b.current===null?(i>0&&b.soc!==null&&bars[i-1].soc!==null&&b.soc>=bars[i-1].soc):b.current>=0,palette=charging?['#3fae54','#69c95b','#91db70','#b7ea8b']:['#b94149','#d65b5d','#e57a70','#f09c8b'];let y=r.height;b.parts.sort((a,b)=>a.id.localeCompare(b.id)).forEach((p,n)=>{const ph=Math.max(0,Math.min(100,p.value))/100*r.height;if(!ph)return;y-=ph;c.fillStyle=palette[n%palette.length];c.fillRect(i*slot+(slot-bw)/2,y,bw,Math.max(1,ph));legend.set(p.id,{name:p.name,color:palette[n%palette.length]})})});const host=root.querySelector('[data-battery-history-legend]');if(host)host.innerHTML=[...legend.values()].map(x=>`<span><i style="background:${x.color}"></i>${esc(x.name)}</span>`).join('')||'<span class="muted">Se necesitan muestras históricas para mostrar aportes.</span>'}
  function queueDraw(root=state.root){if(drawPending||!root)return;drawPending=true;requestAnimationFrame(()=>{drawPending=false;draw(root)})}
  function afterRender(root){state.root=root;root.querySelectorAll('[data-battery-manage]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openManager?.()}));root.querySelectorAll('[data-battery-history-zoom]').forEach(b=>b.addEventListener('click',()=>{const d=b.dataset.batteryHistoryZoom==='in'?1:-1,next=Math.max(0,Math.min(ZOOMS.length-1,zoom+d));if(next!==zoom){zoom=next;write(ZOOM_KEY,zoom);requestRender('batteries')}}));queueDraw(root)}
  function updateBattery(data){if(!data)return;const id=String(data.id||data.address||data.deviceId||data.mac||data.name||'battery');let b=state.batteries.find(x=>String(x.id)===id);if(!b){b={id,name:data.name||data.deviceName||'Batería',capacityAh:num(data.capacityAh)||0,connected:true};state.batteries.push(b)}Object.assign(b,data,{id,connected:data.connected!==false});const s=stats();if(!state.remoteAuthoritative&&s.soc!==null)appendHistory(s);saveCurrent();requestRender('batteries')}
  function addBattery(device){const id=String(device.id||device.address||device.deviceId||device.mac||device.name||Date.now());if(state.batteries.some(b=>String(b.id)===id))return;state.batteries.push({id,name:device.name||device.deviceName||'Batería',deviceName:device.name||device.deviceName||'',address:device.address||device.mac||'',capacityAh:num(device.capacityAh)||0,connected:false});saveCurrent(true);requestRender('batteries')}
  function removeBattery(id){state.batteries=state.batteries.filter(b=>String(b.id)!==String(id));saveCurrent(true);requestRender('batteries')}
  function renameBank(name){const n=String(name||'').trim();if(!n)return;state.bankName=n;saveCurrent(true);requestRender('batteries')}
  // Remote needs the compacted Core history to render the same battery chart.
  function exportRemoteState(){return{bankName:state.bankName,batteries:clone(state.batteries),history:clone(state.history),statsSummary:clone(stats())}}
  function applyRemoteState(remote){if(!remote||typeof remote!=='object')return;state.remoteAuthoritative=true;if(typeof remote.bankName==='string')state.bankName=remote.bankName;if(Array.isArray(remote.batteries))state.batteries=clone(remote.batteries);if(Array.isArray(remote.history))state.history=clone(remote.history);requestRender('batteries')}
  function setScanDevices(list){state.scanDevices=Array.isArray(list)?clone(list):[]}
  function executeRemoteCommand(command,payload){if(command==='battery.add')addBattery(payload?.device||payload);else if(command==='battery.remove')removeBattery(payload?.id);else if(command==='battery.renameBank')renameBank(payload?.name);else if(command==='battery.scan')try{window.BoatStationCore?.openBluetoothScanner?.()||window.NativeBridge?.startBatteryScan?.()}catch{}}
  window.addEventListener('resize',()=>queueDraw());
  window.BoatStationBatteryState={exportRemoteState,applyRemoteState,executeRemoteCommand,setScanDevices,isRemote:()=>state.remoteAuthoritative};
  return{id:'batteries',name:'Baterías',pages:4,summary,page,afterRender,state,updateBattery,addBattery,removeBattery,renameBank,stats,exportRemoteState,applyRemoteState};
}
