export function createGpsModule(requestRender){
  const savedUnits=(()=>{try{return localStorage.getItem('bs.gps.units')||'nautical'}catch(_){return 'nautical'}})();
  const savedCoordFormat=(()=>{try{return localStorage.getItem('bs.gps.coordFormat')||'dd'}catch(_){return 'dd'}})();
  const state={fix:null,recording:false,route:[],importName:'',root:null,remoteAuthoritative:false,units:['nautical','metric','imperial'].includes(savedUnits)?savedUnits:'nautical',coordFormat:['dd','dm','dms'].includes(savedCoordFormat)?savedCoordFormat:'dd'};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const unitDefs={nautical:{label:'Náuticas',speed:'kn',accuracy:'m'},metric:{label:'Métricas',speed:'km/h',accuracy:'m'},imperial:{label:'Imperiales',speed:'mph',accuracy:'ft'}};
  const coordDefs={dd:{label:'Grados decimales'},dm:{label:'Grados y minutos'},dms:{label:'Grados, minutos y segundos'}};
  function unitDef(){return unitDefs[state.units]||unitDefs.nautical}
  function speedValue(f){const kts=Number(f?.speedKts);if(!Number.isFinite(kts))return '—';if(state.units==='metric')return (kts*1.852).toFixed(1);if(state.units==='imperial')return (kts*1.150779).toFixed(1);return kts.toFixed(1)}
  function accuracyValue(f){const m=Number(f?.accuracy);if(!Number.isFinite(m))return '—';return state.units==='imperial'?Math.round(m*3.28084):Math.round(m)}
  function coordValue(value,isLat){const n=Number(value);if(!Number.isFinite(n))return '—';const hemi=isLat?(n<0?'S':'N'):(n<0?'W':'E'),a=Math.abs(n);if(state.coordFormat==='dm'){const d=Math.floor(a),m=(a-d)*60;return `${d}° ${m.toFixed(3)}′ ${hemi}`}if(state.coordFormat==='dms'){const d=Math.floor(a),mins=(a-d)*60,m=Math.floor(mins),s=(mins-m)*60;return `${d}° ${m}′ ${s.toFixed(1)}″ ${hemi}`}return `${a.toFixed(6)}° ${hemi}`}
  function summary(){if(!state.fix)return 'Sin señal';return `${coordValue(state.fix.lat,true)}, ${coordValue(state.fix.lon,false)}`}
  function page(index){
    if(index===0){const f=state.fix||{},u=unitDef();return `<div class="gps-coords"><div class="gps-coord"><div class="value" data-gps-lat>${coordValue(f.lat,true)}</div><div class="label">Latitud</div></div><div class="gps-coord"><div class="value" data-gps-lon>${coordValue(f.lon,false)}</div><div class="label">Longitud</div></div></div><div class="metric-grid three"><div class="metric"><div class="value" data-gps-speed>${speedValue(f)} ${u.speed}</div><div class="label">Velocidad</div></div><div class="metric"><div class="value" data-gps-bearing>${Number.isFinite(Number(f.bearing))?Math.round(Number(f.bearing)):'—'}°</div><div class="label">Rumbo</div></div><div class="metric"><div class="value" data-gps-accuracy>${accuracyValue(f)} ${u.accuracy}</div><div class="label">Precisión</div></div></div>`}
    return `<canvas class="gps-map" data-gps-map></canvas><div class="gps-actions"><button class="gps-action primary" data-gps-action="${state.recording?'stop':'start'}"><span class="gps-action-icon">${state.recording?'■':'●'}</span><span>${state.recording?'Detener grabación':'Iniciar grabación'}</span></button><button class="gps-action" data-gps-action="import"><span class="gps-action-icon">↓</span><span>Importar ruta</span></button><button class="gps-action" data-gps-action="clear" ${state.route.length?'':'disabled'}><span class="gps-action-icon">×</span><span>Limpiar ruta</span></button><button class="gps-action" data-gps-action="export" ${state.route.length?'':'disabled'}><span class="gps-action-icon">↑</span><span>Exportar ruta</span></button></div><div class="gps-status ${state.recording?'gps-rec':''}" data-gps-status>${statusText()}</div><input data-gps-file type="file" accept=".gpx,application/gpx+xml,text/xml" hidden>`}
  function statusText(){return `${state.recording?'● Grabando ruta · ':''}${state.route.length} puntos${state.importName?` · ${esc(state.importName)}`:''}`}
  function setText(selector,value){const el=state.root?.querySelector(selector);if(el&&el.textContent!==value)el.textContent=value}
  function refreshLive(){const root=state.root;if(!root)return;const f=state.fix||{},u=unitDef();const summaryEl=root.querySelector('.summary');if(summaryEl)summaryEl.textContent=summary();setText('[data-gps-lat]',coordValue(f.lat,true));setText('[data-gps-lon]',coordValue(f.lon,false));setText('[data-gps-speed]',`${speedValue(f)} ${u.speed}`);setText('[data-gps-bearing]',`${Number.isFinite(Number(f.bearing))?Math.round(Number(f.bearing)):'—'}°`);setText('[data-gps-accuracy]',`${accuracyValue(f)} ${u.accuracy}`);const status=root.querySelector('[data-gps-status]');if(status){status.textContent=statusText();status.classList.toggle('gps-rec',state.recording)}draw(root)}
  function setUnits(units){if(!unitDefs[units])return;state.units=units;try{localStorage.setItem('bs.gps.units',units)}catch(_){}requestRender('gps')}
  function getUnits(){return state.units}
  function getUnitOptions(){return Object.entries(unitDefs).map(([id,v])=>({id,label:v.label}))}
  function setCoordFormat(format){if(!coordDefs[format])return;state.coordFormat=format;try{localStorage.setItem('bs.gps.coordFormat',format)}catch(_){}requestRender('gps')}
  function getCoordFormat(){return state.coordFormat}
  function getCoordFormatOptions(){return Object.entries(coordDefs).map(([id,v])=>({id,label:v.label}))}
  function update(fix){if(!fix||!Number.isFinite(Number(fix.lat))||!Number.isFinite(Number(fix.lon)))return;state.fix={...fix,lat:Number(fix.lat),lon:Number(fix.lon)};if(state.recording&&!state.remoteAuthoritative){const last=state.route[state.route.length-1],next={lat:state.fix.lat,lon:state.fix.lon,time:state.fix.time||Date.now()};if(!last||last.lat!==next.lat||last.lon!==next.lon)state.route.push(next)}refreshLive()}
  function exportGpx(){if(!state.route.length)return;const pts=state.route.map(p=>`<trkpt lat="${p.lat}" lon="${p.lon}"><time>${new Date(p.time||Date.now()).toISOString()}</time></trkpt>`).join('');const xml=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Boat Station"><trk><name>Boat Station route</name><trkseg>${pts}</trkseg></trk></gpx>`;const url=URL.createObjectURL(new Blob([xml],{type:'application/gpx+xml'})),a=document.createElement('a');a.href=url;a.download=`boat-station-route-${new Date().toISOString().replace(/[:.]/g,'-')}.gpx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function parseGpx(text,name='Ruta importada'){const doc=new DOMParser().parseFromString(String(text),'application/xml');const pts=[...doc.querySelectorAll('trkpt')].map(n=>({lat:Number(n.getAttribute('lat')),lon:Number(n.getAttribute('lon')),time:Date.parse(n.querySelector('time')?.textContent||'')||Date.now()})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));return pts.length?{route:pts,importName:name}:null}
  function applyImportedRoute(data){if(!data||!Array.isArray(data.route)||!data.route.length)return;state.route=data.route.map(p=>({lat:Number(p.lat),lon:Number(p.lon),time:Number(p.time)||Date.now()})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));state.importName=String(data.importName||'Ruta importada');requestRender('gps')}
  function importGpx(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=parseGpx(reader.result,file.name||'Ruta importada');if(!data)return;if(state.remoteAuthoritative){window.BoatStationRemoteCommand?.send?.('gps.import',data);return}applyImportedRoute(data)}catch(_){}};reader.readAsText(file)}
  function localAction(action,root){if(action==='start'){state.recording=true;requestRender('gps')}else if(action==='stop'){state.recording=false;requestRender('gps')}else if(action==='export')exportGpx();else if(action==='import')root.querySelector('[data-gps-file]')?.click();else if(action==='clear'){state.recording=false;state.route=[];state.importName='';requestRender('gps')}}
  function handleAction(action,root){if(state.remoteAuthoritative&&['start','stop','clear'].includes(action)){window.BoatStationRemoteCommand?.send?.(`gps.${action}`);return}localAction(action,root)}
  function draw(root){const canvas=root.querySelector('[data-gps-map]');if(!canvas)return;const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));const ctx=canvas.getContext('2d'),w=rect.width,h=rect.height;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#17394f';ctx.lineWidth=1;for(let i=1;i<5;i++){const x=i*w/5,y=i*h/5;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const route=state.route.slice(),center=state.fix?{lat:state.fix.lat,lon:state.fix.lon}:route.length?route[route.length-1]:null;if(!center){ctx.fillStyle='#94a7b6';ctx.font='13px sans-serif';ctx.fillText('Sin posición GPS',12,22);return}const latScale=Math.max(.2,Math.cos(center.lat*Math.PI/180));let maxDx=0,maxDy=0;for(const p of route){maxDx=Math.max(maxDx,Math.abs((p.lon-center.lon)*latScale));maxDy=Math.max(maxDy,Math.abs(p.lat-center.lat))}const halfSpan=Math.max(.00045,maxDx,maxDy)*1.18,usable=Math.max(40,Math.min(w,h)-36),pxPerDegree=usable/(halfSpan*2),cx=w/2,cy=h/2,sx=lon=>cx+((lon-center.lon)*latScale)*pxPerDegree,sy=lat=>cy-((lat-center.lat)*pxPerDegree);if(route.length>1){ctx.save();ctx.beginPath();ctx.rect(0,0,w,h);ctx.clip();ctx.strokeStyle='#1ed7e5';ctx.lineWidth=2.5;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();route.forEach((p,i)=>i?ctx.lineTo(sx(p.lon),sy(p.lat)):ctx.moveTo(sx(p.lon),sy(p.lat)));ctx.stroke();ctx.restore()}ctx.fillStyle='#8bd332';ctx.beginPath();ctx.arc(cx,cy,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#dfffb9';ctx.lineWidth=1.5;ctx.stroke()}
  function afterRender(root){state.root=root;draw(root);root.querySelectorAll('[data-gps-action]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();handleAction(btn.dataset.gpsAction,root)}));root.querySelector('[data-gps-file]')?.addEventListener('change',e=>importGpx(e.target.files?.[0]))}
  function exportRemoteState(){return{recording:!!state.recording,route:state.route.map(p=>({lat:Number(p.lat),lon:Number(p.lon),time:Number(p.time)||Date.now()})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)),importName:String(state.importName||'')}}
  function applyRemoteState(remote){if(!remote||typeof remote!=='object')return;const previousRecording=state.recording,previousImport=state.importName;state.remoteAuthoritative=true;state.recording=!!remote.recording;state.importName=String(remote.importName||'');state.route=Array.isArray(remote.route)?remote.route.map(p=>({lat:Number(p.lat),lon:Number(p.lon),time:Number(p.time)||Date.now()})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)):[];if(previousRecording!==state.recording||previousImport!==state.importName)requestRender('gps');else refreshLive()}
  function executeRemoteCommand(command,payload){if(command==='gps.start')localAction('start',state.root);else if(command==='gps.stop')localAction('stop',state.root);else if(command==='gps.clear')localAction('clear',state.root);else if(command==='gps.import')applyImportedRoute(payload)}
  window.BoatStationGpsState={exportRemoteState,applyRemoteState,executeRemoteCommand};
  return {id:'gps',name:'GPS',pages:2,summary,page,afterRender,update,state,setUnits,getUnits,getUnitOptions,setCoordFormat,getCoordFormat,getCoordFormatOptions};
}
