export function createPhoneModule(requestRender){
  const state={data:null};
  const num=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
  function normalized(){const d=state.data||{};return{battery:Number.isFinite(Number(d.battery))?Number(d.battery):Number.isFinite(Number(d.level))?Number(d.level):null,charging:!!d.charging,temp:Number.isFinite(Number(d.batteryTemp))?Number(d.batteryTemp):Number.isFinite(Number(d.temperatureC))?Number(d.temperatureC):null,network:d.network||'—',model:d.model||[d.manufacturer,d.deviceModel].filter(Boolean).join(' ')||'—',android:d.android||'—',voltage:Number.isFinite(Number(d.voltageV))?Number(d.voltageV):null}}
  function summary(){const d=normalized();return d.battery===null?'Sin datos':`${Math.round(d.battery)}% · ${d.charging?'Cargando':'Batería'}`}
  function page(i){const d=normalized();if(i===0)return `<div class="metric-grid three"><div class="metric"><div class="value">${d.battery===null?'—':Math.round(d.battery)+'%'}</div><div class="label">Batería</div></div><div class="metric"><div class="value">${d.temp===null?'—':num(d.temp)+' °C'}</div><div class="label">Temperatura</div></div><div class="metric"><div class="value">${d.charging?'Sí':'No'}</div><div class="label">Cargando</div></div></div><div class="metric-grid" style="margin-top:8px"><div class="metric"><div class="value" style="font-size:16px">${d.network}</div><div class="label">Red</div></div><div class="metric"><div class="value" style="font-size:16px">${d.voltage===null?'—':num(d.voltage,2)+' V'}</div><div class="label">Voltaje</div></div></div>`;return `<div class="metric-grid"><div class="metric"><div class="value" style="font-size:16px">${d.model}</div><div class="label">Dispositivo</div></div><div class="metric"><div class="value" style="font-size:16px">${d.android}</div><div class="label">Android</div></div></div>`}
  function update(data){state.data=data||{};requestRender('phone')}
  return{id:'phone',name:'Estado del teléfono',pages:2,summary,page,update,state};
}
