export function createSeaStateModule(requestRender){
  const HISTORY_HOUR_LEVELS=[1,3,6,12,24,48,72,168,336,720,1440,2160];
  const read=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch{return fallback}};
  const savedHistory=read('bs.seastate.history',[]),savedHours=Number(localStorage.getItem('bs.seastate.historyHours')||24);
  const state={motion:0,samples:[],average:0,peak:0,wave:0,factor:Number(localStorage.getItem('bs.seaFactor')||1),history:Array.isArray(savedHistory)?savedHistory:[],historyHours:HISTORY_HOUR_LEVELS.includes(savedHours)?savedHours:24,lastHistoryAt:0,root:null};
  function saveHistory(){try{localStorage.setItem('bs.seastate.history',JSON.stringify(state.history));localStorage.setItem('bs.seastate.historyHours',String(state.historyHours))}catch{}}
  function recalc(){const now=Date.now();state.samples=state.samples.filter(x=>now-x.t<=30000);if(!state.samples.length){state.average=state.peak=state.wave=0;return}let sum=0,peak=0;for(const x of state.samples){sum+=x.v;if(x.v>peak)peak=x.v}state.average=sum/state.samples.length;state.peak=peak;state.wave=state.average*Math.max(0,Number(state.factor)||0)}
  function summary(){return`${state.wave.toFixed(2)} m · mov ${state.average.toFixed(2)}`}
  function rangeLabel(){const h=Number(state.historyHours);if(h<24)return`${h} ${h===1?'hora':'horas'}`;const d=h/24;return`${d} ${d===1?'día':'días'}`}
  function currentPage(){return`<div class="battery-hero"><div class="battery-bank-name" style="font-size:34px">${state.wave.toFixed(2)} m</div><div class="battery-ah">Altura de ola estimada · promedio móvil 30 s</div></div><div class="metric-grid"><div class="metric"><div class="value">${state.average.toFixed(2)}</div><div class="label">Movimiento promedio</div></div><div class="metric"><div class="value">${state.peak.toFixed(2)}</div><div class="label">Pico</div></div></div>`}
  function visibleHistory(){const cutoff=Date.now()-Number(state.historyHours)*3600000;return state.history.filter(p=>Number(p.time)>=cutoff&&Number.isFinite(Number(p.intensity)))}
  function visibleAverage(){const pts=visibleHistory();if(!pts.length)return null;let sum=0;for(const p of pts)sum+=Number(p.intensity);return sum/pts.length}
  function historyPage(){const avg=visibleAverage();return`<div class="battery-history-wrap"><div class="battery-history"><canvas data-seastate-chart></canvas><div class="battery-history-note">Intensidad registrada · ${rangeLabel()} · Promedio: <strong data-seastate-average>${avg===null?'—':avg.toFixed(2)}</strong></div></div><div class="battery-history-zoom" aria-label="Zoom del historial"><button type="button" data-seastate-zoom="out" aria-label="Mostrar más historial">+</button><button type="button" data-seastate-zoom="in" aria-label="Mostrar menos historial">−</button></div></div>`}
  function page(i){return i===0?currentPage():historyPage()}
  function chartVisible(root){return !!root&&window.BoatStationPageLayout?.currentPage?.(root)===1}
  function aggregate(points,start,end,count){const step=Math.max(1,(end-start)/count),buckets=Array.from({length:count},()=>({sum:0,n:0}));for(const p of points){const i=Math.max(0,Math.min(count-1,Math.floor((Number(p.time)-start)/step))),b=buckets[i];b.sum+=Number(p.intensity)||0;b.n++}return buckets.map(b=>b.n?b.sum/b.n:null)}
  function markGranularity(hours){if(hours<=1)return 5*60000;if(hours<=3)return 15*60000;if(hours<=6)return 30*60000;if(hours<=24)return 60*60000;if(hours<=72)return 2*3600000;if(hours<=336)return 6*3600000;if(hours<=720)return 12*3600000;return 24*3600000}
  function axisLabel(time,hours){const d=new Date(time),hh=String(d.getHours()).padStart(2,'0'),mm=String(d.getMinutes()).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0'),month=String(d.getMonth()+1).padStart(2,'0');if(hours<=12)return`${hh}:${mm}`;if(hours<=72)return`${day}/${month} ${hh}:${mm}`;if(hours<=336)return`${day}/${month} ${hh}h`;return`${day}/${month}`}
  function drawChart(root){if(!chartVisible(root))return;const canvas=root.querySelector('[data-seastate-chart]');if(!canvas)return;const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const dpr=window.devicePixelRatio||1,pw=Math.round(r.width*dpr),ph=Math.round(r.height*dpr);if(canvas.width!==pw)canvas.width=pw;if(canvas.height!==ph)canvas.height=ph;const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,r.width,r.height);const hours=Number(state.historyHours),axisH=r.width<520?42:30,plotH=Math.max(20,r.height-axisH),end=Date.now(),start=end-hours*3600000,slot=r.width/12,pts=aggregate(visibleHistory(),start,end,12),values=pts.filter(v=>v!==null),max=Math.max(1,...values);c.strokeStyle='#17394f';c.lineWidth=1;for(let i=1;i<5;i++){const y=i*plotH/5;c.beginPath();c.moveTo(0,y);c.lineTo(r.width,y);c.stroke()}const bar=Math.max(1,slot*.7);pts.forEach((v,i)=>{if(v===null)return;const h=Math.max(1,(v/max)*plotH),x=i*slot+(slot-bar)/2;c.fillStyle='#1ed7e5';c.fillRect(x,plotH-h,bar,h)});c.font=(r.width<520?'8px':'9px')+' system-ui, sans-serif';c.fillStyle='#7890a1';c.textBaseline='middle';c.textAlign='center';const mark=markGranularity(hours);for(let i=0;i<12;i++){const center=start+(i+.5)*(end-start)/12,time=Math.round(center/mark)*mark,text=axisLabel(time,hours),x=(i+.5)*slot,y=plotH+axisH/2;c.save();c.translate(x,y);if(r.width<520)c.rotate(-Math.PI/4);c.fillText(text,0,0);c.restore()}}
  function compactHistory(){const now=Date.now(),cutoff=now-90*86400000,src=state.history.filter(p=>Number(p.time)>=cutoff&&Number.isFinite(Number(p.intensity))).sort((a,b)=>a.time-b.time),bins=new Map();for(const p of src){const age=now-Number(p.time);let bucket=30000;if(age>14*86400000)bucket=7200000;else if(age>48*3600000)bucket=1800000;else if(age>6*3600000)bucket=300000;const key=Math.floor(Number(p.time)/bucket)*bucket,prev=bins.get(key);if(prev){prev.sum+=Number(p.intensity);prev.n++;prev.time=Math.max(prev.time,Number(p.time))}else bins.set(key,{time:Number(p.time),sum:Number(p.intensity),n:1})}state.history=[...bins.values()].map(b=>({time:b.time,intensity:b.sum/b.n})).sort((a,b)=>a.time-b.time)}
  function appendHistory(){const now=Date.now();if(now-state.lastHistoryAt<30000)return;state.lastHistoryAt=now;state.history.push({time:now,intensity:state.average});if(state.history.length%120===0)compactHistory();saveHistory()}
  function changeZoom(direction){const i=HISTORY_HOUR_LEVELS.indexOf(Number(state.historyHours)),next=direction==='out'?Math.min(HISTORY_HOUR_LEVELS.length-1,i+1):Math.max(0,i-1);if(next===i)return;state.historyHours=HISTORY_HOUR_LEVELS[next];saveHistory();requestRender('seastate')}
  function afterRender(root){state.root=root;if(chartVisible(root))drawChart(root);root.querySelectorAll('[data-seastate-zoom]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();changeZoom(b.dataset.seastateZoom)}))}
  function update(value){const v=Number(value);if(!Number.isFinite(v))return;state.motion=v;state.samples.push({t:Date.now(),v:Math.max(0,v)});recalc();appendHistory();requestRender('seastate')}
  return{id:'seastate',name:'Sea State',pages:2,summary,page,afterRender,update,state};
}
