export const STORAGE_KEYS={tree:'adventureStudioProjectTreeV1',selection:'adventureStudioProjectSelectionV1',activeEditor:'adventureStudioActiveEditorV1',resources:'adventureStudioResourcesV1',settings:'adventureStudioGameSettingsV1',projectWidth:'adventureStudioProjectWidth',inspectorWidth:'adventureStudioInspectorWidth'};
export const ROOTS=[{id:'game',label:'Game',itemType:'game',icon:'◆',fixed:true},{id:'rooms',label:'Rooms',itemType:'room',icon:'▧'},{id:'characters',label:'Characters',itemType:'character',icon:'◉'},{id:'inventory',label:'Inventory',itemType:'inventory',icon:'◇'},{id:'dialogues',label:'Dialogues',itemType:'dialogue',icon:'◌'},{id:'audio',label:'Audio',itemType:'audio',icon:'♪'}];
export const TYPES={room:{label:'Room',editor:'Room Editor',rootId:'rooms',icon:'▧'},character:{label:'Character',editor:'Character Editor',rootId:'characters',icon:'◉'},inventory:{label:'Inventory Element',editor:'Inventory Editor',rootId:'inventory',icon:'◇'},dialogue:{label:'Dialogue',editor:'Dialogue Editor',rootId:'dialogues',icon:'◌'},audio:{label:'Audio',editor:'Audio Editor',rootId:'audio',icon:'♪'}};
export const GAME_SECTIONS=[{key:'settings',label:'Settings',icon:'⚙'}];
export const ROOM_SECTIONS=[{key:'backgrounds',label:'Backgrounds',accepts:'background',icon:'▣'},{key:'characters',label:'Characters',accepts:'character',icon:'◉'},{key:'objects',label:'Objects',accepts:'object',icon:'□'},{key:'inventory',label:'Inventory',accepts:'inventory',icon:'◇'},{key:'audio',label:'Audio',accepts:'audio',icon:'♪'},{key:'dialogues',label:'Dialogues',accepts:'dialogue',icon:'◌'},{key:'hotspots',label:'Hotspots',accepts:'hotspot',icon:'⌖'},{key:'walkAreas',label:'Walk Areas',accepts:'walkArea',icon:'⌁'},{key:'entrances',label:'Entrances',accepts:'entrance',icon:'⇥'}];
export function uid(prefix){return`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
export function createGameSections(){return GAME_SECTIONS.map(section=>({id:`game:section:${section.key}`,kind:'game-section',label:section.label,sectionKey:section.key,icon:section.icon}));}
export function initialTree(){return ROOTS.map(root=>root.id==='game'?{id:'game',kind:'root',label:'Game',itemType:'game',open:true,children:createGameSections()}:{id:root.id,kind:'root',label:root.label,itemType:root.itemType,open:false,children:[]});}
export function createRoomSections(roomId){return ROOM_SECTIONS.map(section=>({id:`${roomId}:section:${section.key}`,kind:'room-section',label:section.label,sectionKey:section.key,accepts:section.accepts,icon:section.icon,roomId,open:false,children:[]}));}
function normalizeGameSections(children){const saved=Array.isArray(children)?children:[];return GAME_SECTIONS.map(def=>{const old=saved.find(node=>node?.kind==='game-section'&&node.sectionKey===def.key);return{id:`game:section:${def.key}`,kind:'game-section',label:def.label,sectionKey:def.key,icon:def.icon,open:old?.open===true};});}
function normalizeReference(node,roomId,section){if(!node||node.kind!=='reference'||typeof node.resourceId!=='string'||node.itemType!==section.accepts)return null;return{id:node.id||uid('ref'),kind:'reference',resourceId:node.resourceId,itemType:node.itemType,roomId,sectionKey:section.key};}
function normalizeRoomSections(roomId,children){const saved=Array.isArray(children)?children:[];return ROOM_SECTIONS.map(def=>{const old=saved.find(node=>node?.kind==='room-section'&&node.sectionKey===def.key);return{id:`${roomId}:section:${def.key}`,kind:'room-section',label:def.label,sectionKey:def.key,accepts:def.accepts,icon:def.icon,roomId,open:old?.open===true,children:Array.isArray(old?.children)?old.children.map(child=>normalizeReference(child,roomId,def)).filter(Boolean):[]};});}
function normalizeNode(node,rootId){if(!node||typeof node!=='object'||typeof node.id!=='string'||typeof node.label!=='string')return null;if(node.kind==='folder')return{id:node.id,kind:'folder',label:node.label,rootId,open:node.open===true,children:Array.isArray(node.children)?node.children.map(child=>normalizeNode(child,rootId)).filter(Boolean):[]};if(node.kind!=='item')return null;const expected=ROOTS.find(root=>root.id===rootId)?.itemType;const itemType=TYPES[node.itemType]?.rootId===rootId?node.itemType:expected;if(!itemType||itemType==='game')return null;const item={id:node.id,kind:'item',label:node.label,rootId,itemType};if(itemType==='room'){item.open=node.open===true;item.children=normalizeRoomSections(item.id,node.children);}return item;}
export function loadTree(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEYS.tree)||'null');if(!Array.isArray(parsed))return initialTree();return ROOTS.map(def=>{const saved=parsed.find(node=>node?.id===def.id&&node.kind==='root');if(def.id==='game')return{id:'game',kind:'root',label:'Game',itemType:'game',open:saved?.open!==false,children:normalizeGameSections(saved?.children)};return{id:def.id,kind:'root',label:def.label,itemType:def.itemType,open:saved?.open===true,children:Array.isArray(saved?.children)?saved.children.map(child=>normalizeNode(child,def.id)).filter(Boolean):[]};});}catch{return initialTree();}}
export function loadResources(){try{const resources=JSON.parse(localStorage.getItem(STORAGE_KEYS.resources)||'null');return resources&&typeof resources==='object'?resources:{rooms:{},characters:{},inventory:{},dialogues:{},audio:{}};}catch{return{rooms:{},characters:{},inventory:{},dialogues:{},audio:{}};}}
export function loadSettings(){try{const stored=JSON.parse(localStorage.getItem(STORAGE_KEYS.settings)||'null');return{width:Number(stored?.width)||1280,height:Number(stored?.height)||720};}catch{return{width:1280,height:720};}}
export function walk(nodes,visitor,parent=null,rootId=null){for(const node of nodes){const current=node.kind==='root'?node.id:rootId;if(visitor(node,parent,current)===false)return false;if(Array.isArray(node.children)&&walk(node.children,visitor,node,current)===false)return false;}return true;}
export function findNode(tree,id){let found=null;walk(tree,(node,parent,rootId)=>{if(node.id===id){found={node,parent,rootId};return false;}});return found;}
export function bucketFor(type){return type==='room'?'rooms':type==='character'?'characters':type==='inventory'?'inventory':type==='dialogue'?'dialogues':'audio';}
export function ensureResource(resources,node){if(!node||node.kind!=='item')return null;const bucket=bucketFor(node.itemType);resources[bucket]??={};if(!resources[bucket][node.id])resources[bucket][node.id]=node.itemType==='room'?{id:node.id,type:'room',backgrounds:[],defaultBackgroundId:null}:{id:node.id,type:node.itemType};const resource=resources[bucket][node.id];if(node.itemType==='room'){resource.backgrounds=Array.isArray(resource.backgrounds)?resource.backgrounds:[];if(resource.background&&resource.backgrounds.length===0){const legacyId=`${node.id}:background:default`;resource.backgrounds.push({id:legacyId,name:resource.background.name||'Default',assetKey:node.id,width:resource.background.width,height:resource.background.height,type:resource.background.type,size:resource.background.size,zoom:resource.zoom||100,scaleMode:resource.scaleMode||'manual'});resource.defaultBackgroundId=legacyId;delete resource.background;delete resource.zoom;delete resource.scaleMode;}if(!resource.defaultBackgroundId&&resource.backgrounds[0])resource.defaultBackgroundId=resource.backgrounds[0].id;}return resource;}
export function removeReferencesTo(tree,resourceId){walk(tree,node=>{if(Array.isArray(node.children))node.children=node.children.filter(child=>!(child.kind==='reference'&&child.resourceId===resourceId));});}
export function createReference(section,resourceNode){if(section.kind!=='room-section'||resourceNode.kind!=='item'||section.accepts!==resourceNode.itemType)return null;if(section.children.some(reference=>reference.resourceId===resourceNode.id))return null;return{id:uid('ref'),kind:'reference',resourceId:resourceNode.id,itemType:resourceNode.itemType,roomId:section.roomId,sectionKey:section.sectionKey};}
export function saveProject({tree,resources,settings,selectedId,activeEditorId}){localStorage.setItem(STORAGE_KEYS.tree,JSON.stringify(tree));localStorage.setItem(STORAGE_KEYS.resources,JSON.stringify(resources));localStorage.setItem(STORAGE_KEYS.settings,JSON.stringify(settings));localStorage.setItem(STORAGE_KEYS.selection,selectedId);activeEditorId?localStorage.setItem(STORAGE_KEYS.activeEditor,activeEditorId):localStorage.removeItem(STORAGE_KEYS.activeEditor);}