import{ROOTS,TYPES,findNode,walk,uid,createRoomSections,createReference}from'./project-model.js';

export function createProjectTreeController({treeElement,menuElement,getTree,getSelectedId,setSelectedId,save,openEditor,onDeleteResource}){
  let activeCreateTargetId=null;let draggedId=null;let renameTimer=null;
  const tree=()=>getTree();
  const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const countItems=node=>node.kind==='item'&&node.itemType!=='room'?1:Array.isArray(node.children)?node.children.reduce((s,c)=>s+countItems(c),0):0;
  const resourceLabel=id=>findNode(tree(),id)?.node?.label||'Missing resource';

  function renderNode(node){const selected=node.id===getSelectedId()?' selected':'';
    if(node.kind==='root'){const def=ROOTS.find(r=>r.id===node.id);return`<div class="tree-root ${node.open?'':'closed'}" data-node-id="${node.id}" data-drop-container="true"><div class="tree-root-row${selected}"><button class="tree-expander" data-action="toggle" data-node-id="${node.id}"><span class="tree-chevron">⌄</span></button><button class="tree-node-select" data-action="select" data-node-id="${node.id}"><span class="tree-type-icon">${def?.icon||'▱'}</span><span class="tree-root-name">${esc(node.label)}</span><span class="tree-count">${countItems(node)}</span></button><button class="tree-create" data-action="create-menu" data-node-id="${node.id}">＋</button></div><div class="tree-children">${node.children.length?node.children.map(renderNode).join(''):'<div class="tree-empty">Empty</div>'}</div></div>`;}
    if(node.kind==='folder')return`<div class="tree-folder ${node.open?'':'closed'}" data-node-id="${node.id}" data-draggable-node="true" data-drop-container="true" draggable="true"><div class="tree-folder-row${selected}"><button class="tree-expander" data-action="toggle" data-node-id="${node.id}"><span class="tree-chevron">⌄</span></button><span class="tree-type-icon tree-select-icon" data-action="select" data-node-id="${node.id}">▱</span><button class="tree-name-button" data-action="rename" data-node-id="${node.id}"><span class="tree-folder-name">${esc(node.label)}</span></button><button class="tree-create" data-action="create-menu" data-node-id="${node.id}">＋</button><button class="tree-delete" data-action="delete" data-node-id="${node.id}">×</button></div><div class="tree-children">${node.children.length?node.children.map(renderNode).join(''):'<div class="tree-empty">Empty</div>'}</div></div>`;
    if(node.kind==='room-section')return`<div class="tree-room-section ${node.open?'':'closed'}" data-node-id="${node.id}" data-drop-container="true"><div class="tree-section-row${selected}"><button class="tree-expander" data-action="toggle" data-node-id="${node.id}"><span class="tree-chevron">⌄</span></button><button class="tree-node-select" data-action="select" data-node-id="${node.id}"><span class="tree-type-icon">${node.icon}</span><span class="tree-section-name">${esc(node.label)}</span><span class="tree-count">${node.children.length}</span></button></div><div class="tree-children">${node.children.length?node.children.map(renderNode).join(''):'<div class="tree-empty">Empty</div>'}</div></div>`;
    if(node.kind==='reference'){const type=TYPES[node.itemType];return`<div class="tree-reference" data-node-id="${node.id}"><div class="tree-reference-row${selected}"><span class="tree-expander-placeholder"></span><span class="tree-reference-link">↗</span><button class="tree-node-select" data-action="open-reference" data-node-id="${node.id}"><span class="tree-type-icon">${type?.icon||'•'}</span><span class="tree-item-name">${esc(resourceLabel(node.resourceId))}</span></button><button class="tree-delete" data-action="delete-reference" data-node-id="${node.id}">×</button></div></div>`;}
    const def=TYPES[node.itemType];
    if(node.itemType==='room')return`<div class="tree-item tree-room ${node.open?'':'closed'}" data-node-id="${node.id}" data-draggable-node="true" draggable="true"><div class="tree-item-row${selected}"><button class="tree-expander" data-action="toggle" data-node-id="${node.id}"><span class="tree-chevron">⌄</span></button><span class="tree-type-icon tree-select-icon" data-action="select" data-node-id="${node.id}">${def.icon}</span><button class="tree-name-button" data-action="rename" data-node-id="${node.id}"><span class="tree-item-name">${esc(node.label)}</span></button><button class="tree-delete" data-action="delete" data-node-id="${node.id}">×</button></div><div class="tree-children">${node.children.map(renderNode).join('')}</div></div>`;
    return`<div class="tree-item" data-node-id="${node.id}" data-draggable-node="true" draggable="true"><div class="tree-item-row${selected}"><span class="tree-expander-placeholder"></span><span class="tree-type-icon tree-select-icon" data-action="select" data-node-id="${node.id}">${def?.icon||'•'}</span><button class="tree-name-button" data-action="rename" data-node-id="${node.id}"><span class="tree-item-name">${esc(node.label)}</span></button><button class="tree-delete" data-action="delete" data-node-id="${node.id}">×</button></div></div>`;
  }

  function render(){treeElement.innerHTML=tree().map(renderNode).join('');}
  function select(id){if(!findNode(tree(),id))return;setSelectedId(id);save();render();}
  function toggle(id){const f=findNode(tree(),id);if(!f||!Array.isArray(f.node.children))return;f.node.open=!f.node.open;save();render();}
  function openFolder(id){const f=findNode(tree(),id);if(!f||!Array.isArray(f.node.children))return;if(!f.node.open){f.node.open=true;save();render();}}
  function deleteReference(id){const f=findNode(tree(),id);if(!f||f.node.kind!=='reference'||!f.parent)return;f.parent.children=f.parent.children.filter(c=>c.id!==id);setSelectedId(f.parent.id);save();render();}
  function deleteNode(id){const f=findNode(tree(),id);if(!f||f.node.kind==='root'||f.node.kind==='room-section'||f.node.kind==='reference'||!f.parent)return;onDeleteResource(f.node);f.parent.children=f.parent.children.filter(c=>c.id!==id);setSelectedId(f.parent.id);save();render();}
  function startRename(id){requestAnimationFrame(()=>{const f=findNode(tree(),id);if(!f||!['folder','item'].includes(f.node.kind))return;const name=treeElement.querySelector(`[data-node-id="${CSS.escape(id)}"] .tree-folder-name, [data-node-id="${CSS.escape(id)}"] .tree-item-name`);if(!name)return;setSelectedId(id);const input=document.createElement('input');input.className='tree-rename-input';input.value=f.node.label;name.parentElement.replaceWith(input);input.focus();input.select();let done=false;const commit=()=>{if(done)return;done=true;const value=input.value.trim();if(value)f.node.label=value;save();render();};input.addEventListener('keydown',e=>{if(e.key==='Enter')commit();if(e.key==='Escape'){done=true;render();}});input.addEventListener('blur',commit,{once:true});});}
  function scheduleRename(id){clearTimeout(renameTimer);renameTimer=setTimeout(()=>{renameTimer=null;startRename(id);},220);}function cancelRename(){if(renameTimer!==null){clearTimeout(renameTimer);renameTimer=null;}}
  function nextName(type){let n=0;walk(tree(),node=>{if(node.kind==='item'&&node.itemType===type)n++;});return`${TYPES[type].label} ${n+1}`;}
  function createEntry(targetId,type){const f=findNode(tree(),targetId);if(!f||!['root','folder'].includes(f.node.kind))return;const target=f.node;if(type==='folder'){const folder={id:uid('folder'),kind:'folder',label:'New Folder',rootId:f.rootId,open:false,children:[]};target.children.push(folder);target.open=true;setSelectedId(folder.id);save();render();startRename(folder.id);return;}const root=ROOTS.find(r=>r.id===f.rootId);if(!root||type!==root.itemType)return;const item={id:uid(type),kind:'item',label:nextName(type),rootId:f.rootId,itemType:type};if(type==='room'){item.open=false;item.children=createRoomSections(item.id);}target.children.push(item);target.open=true;setSelectedId(item.id);save();render();startRename(item.id);}
  function buildMenu(id){const f=findNode(tree(),id);if(!f||!['root','folder'].includes(f.node.kind))return'';const root=ROOTS.find(r=>r.id===f.rootId),type=TYPES[root?.itemType];if(!root||!type)return'';return`<div class="create-menu-label">Create in ${esc(f.node.label)}</div><button data-create-type="${root.itemType}"><span>${type.icon}</span><div><strong>${esc(type.label)}</strong><small>Add to this folder</small></div></button><div class="create-menu-separator"></div><button data-create-type="folder"><span>▱</span><div><strong>Subfolder</strong><small>Create a nested folder</small></div></button>`;}
  function openMenu(id,anchor){const html=buildMenu(id);if(!html)return;activeCreateTargetId=id;menuElement.innerHTML=html;const r=anchor.getBoundingClientRect();menuElement.style.left=`${Math.min(innerWidth-228,Math.max(8,r.right+6))}px`;menuElement.style.top=`${Math.min(innerHeight-130,r.top-4)}px`;menuElement.classList.add('open');}
  function closeMenu(){activeCreateTargetId=null;menuElement.classList.remove('open');menuElement.innerHTML='';}
  function isDescendant(node,id){return Array.isArray(node.children)&&node.children.some(c=>c.id===id||isDescendant(c,id));}
  function canMoveMaster(d,t){if(!d||!t||d.node.kind==='root'||!['root','folder'].includes(t.node.kind)||d.rootId!==t.rootId)return false;if(d.node.kind==='folder'&&isDescendant(d.node,t.node.id))return false;if(d.parent?.id===t.node.id)return false;return['folder','item'].includes(d.node.kind);}
  function canReference(d,t){return d?.node.kind==='item'&&d.node.itemType!=='room'&&t?.node.kind==='room-section'&&d.node.itemType===t.node.accepts&&!t.node.children.some(r=>r.resourceId===d.node.id);}
  function canDrop(dragId,targetId){const d=findNode(tree(),dragId),t=findNode(tree(),targetId);return canReference(d,t)||canMoveMaster(d,t);}
  function dropNode(dragId,targetId){const d=findNode(tree(),dragId),t=findNode(tree(),targetId);if(canReference(d,t)){const ref=createReference(t.node,d.node);if(ref){t.node.children.push(ref);t.node.open=true;setSelectedId(ref.id);save();render();}return;}if(!canMoveMaster(d,t))return;const i=d.parent.children.findIndex(c=>c.id===dragId);if(i<0)return;const[moved]=d.parent.children.splice(i,1);t.node.children.push(moved);setSelectedId(moved.id);save();render();}
  function clearDrop(){treeElement.querySelectorAll('.drop-valid,.drop-invalid,.dragging-node').forEach(el=>el.classList.remove('drop-valid','drop-invalid','dragging-node'));}

  function bind(){
    treeElement.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(!a)return;const{action,nodeId}=a.dataset;if(action==='toggle')toggle(nodeId);if(action==='select')select(nodeId);if(action==='rename')scheduleRename(nodeId);if(action==='delete')deleteNode(nodeId);if(action==='delete-reference')deleteReference(nodeId);if(action==='open-reference'){const f=findNode(tree(),nodeId);if(f?.node.kind==='reference')openEditor(f.node.resourceId);}if(action==='create-menu'){e.stopPropagation();select(nodeId);openMenu(nodeId,a);}});
    treeElement.addEventListener('dblclick',e=>{cancelRename();const el=e.target.closest('[data-node-id]');if(!el)return;const f=findNode(tree(),el.dataset.nodeId);if(!f)return;if(f.node.kind==='reference')openEditor(f.node.resourceId);else if(f.node.kind==='item')openEditor(f.node.id);else openFolder(f.node.id);});
    treeElement.addEventListener('dragstart',e=>{cancelRename();const el=e.target.closest('[data-draggable-node="true"]');if(!el)return;draggedId=el.dataset.nodeId;el.classList.add('dragging-node');e.dataTransfer.effectAllowed='copyMove';e.dataTransfer.setData('text/plain',draggedId);closeMenu();});
    treeElement.addEventListener('dragover',e=>{if(!draggedId)return;const target=e.target.closest('[data-drop-container="true"]');if(!target)return;e.preventDefault();const valid=canDrop(draggedId,target.dataset.nodeId);e.dataTransfer.dropEffect=valid?(findNode(tree(),target.dataset.nodeId)?.node.kind==='room-section'?'copy':'move'):'none';treeElement.querySelectorAll('.drop-valid,.drop-invalid').forEach(el=>el.classList.remove('drop-valid','drop-invalid'));target.classList.add(valid?'drop-valid':'drop-invalid');});
    treeElement.addEventListener('drop',e=>{if(!draggedId)return;const target=e.target.closest('[data-drop-container="true"]');if(target){e.preventDefault();dropNode(draggedId,target.dataset.nodeId);}draggedId=null;clearDrop();});
    treeElement.addEventListener('dragend',()=>{draggedId=null;clearDrop();});
    menuElement.addEventListener('click',e=>{const b=e.target.closest('[data-create-type]');if(!b||!activeCreateTargetId)return;const target=activeCreateTargetId;closeMenu();createEntry(target,b.dataset.createType);});
    document.addEventListener('click',e=>{if(!menuElement.contains(e.target)&&!e.target.closest('[data-action="create-menu"]'))closeMenu();});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelRename();closeMenu();}});
  }
  return{bind,render};
}