(function(){
  const q=(s,r)=> (r||document).querySelector(s), qa=(s,r)=>Array.from((r||document).querySelectorAll(s));
  const VERSION='0.2.0';
  const css=document.createElement('style');css.id='bs-v200-style';css.textContent=`
    .battery-card .name{font-size:20px!important}.battery-card .bankline{font-size:15px!important;line-height:1.45!important;font-weight:650!important;color:#c7d9e3!important}
    .eta-indicator{margin-top:8px;padding:8px 10px;border:1px solid #1b4058;border-radius:11px;background:#0b2639;color:#9fdce6;font-size:13px;font-weight:700}
    .chartwrap{position:relative!important;margin-left:22px!important;margin-bottom:24px!important;overflow:visible!important}.axis-y{position:absolute;left:-31px;top:50%;transform:translateY(-50%) rotate(-90deg);font-size:10px;color:#8ea5b6;white-space:nowrap}.axis-x{position:absolute;bottom:-21px;left:50%;transform:translateX(-50%);font-size:10px;color:#8ea5b6}.legend{font-size:11px!important;gap:10px!important}.legend:before{content:'Leyenda:';font-weight:800;color:#c7d9e3;margin-right:2px}
    .gps-coords-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.gps-coords-row .gpsline{font-size:18px!important;letter-spacing:-.2px!important;background:#0a2537;border:1px solid #173d55;border-radius:11px;padding:10px 8px;text-align:center;overflow:hidden;text-overflow:ellipsis}
    .route-panel{margin-top:12px}.route-map{width:100%;aspect-ratio:1/1;display:block;border:1px solid #1b4058;border-radius:16px;background:#071b29}.route-controls{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.route-state{font-size:12px;color:#8ea5b6;margin:7px 2px}.route-recording{color:#ff7f87!important;font-weight:800}.route-controls .btn{min-height:40px!important;padding:9px 8px!important;font-size:12px!important}
    .eta-setting{margin-top:10px}.latest-apk-link{text-decoration:none;display:inline-flex;align-items:center;justify-content:center}
  `;document.head.appendChild(css);

  function setVersion(){qa('#menuSheet .option').forEach(r=>{if((r.textContent||'').trim().startsWith('Versión')){const s=q('small',r);if(s)s.textContent=VERSION}})}
  function ensureLatestApkLink(){const inner=q('#menuSheet .sheet-inner');if(!inner||q('#latestApkRow',inner))return;const row=document.createElement('div');row.className='option';row.id='latestApkRow';row.innerHTML='<span>Boat Station APK<br><small class="sub">Última versión disponible</small></span><a class="btn latest-apk-link" href="/BoatStation.apk" download>Descargar APK</a>';const versionRow=qa('.option',inner).find(r=>(r.textContent||'').trim().startsWith('Versión'));if(versionRow&&versionRow.nextSibling)inner.insertBefore(row,versionRow.nextSibling);else inner.appendChild(row)}
  function arrangeGps(){const card=q('#cards>.card[data-id="gps"],#cards>.card[data-kind="gps"]');if(!card)return;const lines=qa('.gpsline',card);if(lines.length>=2&&!lines[0].parentElement.classList.contains('gps-coords-row')){const row=document.createElement('div');row.className='gps-coords-row';lines[0].parentNode.insertBefore(row,lines[0]);row.append(lines[0],lines[1])}}
  function decorateCharts(){qa('.chartwrap').forEach(w=>{if(!q('.axis-y',w)){const y=document.createElement('div');y.className='axis-y';y.textContent='Carga (%)';w.appendChild(y)}if(!q('.axis-x',w)){const x=document.createElement('div');x.className='axis-x';x.textContent='Tiempo';w.appendChild(x)}})}

  const etaSamples=new Map();
  function parseElectrical(el){const t=(el.textContent||'').replace(/,/g,'.');const ah=t.match(/(-?\d+(?:\.\d+)?)\s*Ah\s*\/\s*(-?\d+(?:\.\d+)?)\s*Ah/i);const a=[...t.matchAll(/(-?\d+(?:\.\d+)?)\s*A(?!h)/gi)];if(!ah||!a.length)return null;return{remaining:Number(ah[1]),capacity:Number(ah[2]),current:Number(a[a.length-1][1])}}
  function fmtHours(h){if(!isFinite(h)||h<0)return'Estimación no disponible';const mins=Math.round(h*60);if(mins<60)return mins+' min';const hh=Math.floor(mins/60),mm=mins%60;return hh+' h '+String(mm).padStart(2,'0')+' min'}
  function etaTick(){const windowSec=Number(localStorage.getItem('bs.etaWindow')||30),now=Date.now();qa('.battery-card,.bank').forEach((el,i)=>{const d=parseElectrical(el);if(!d)return;const key=el.dataset.id||el.getAttribute('data-battery-id')||el.getAttribute('data-id')||('eta-'+i);let arr=etaSamples.get(key)||[];arr.push({t:now,c:d.current});arr=arr.filter(x=>now-x.t<=windowSec*1000);etaSamples.set(key,arr);const avg=arr.reduce((s,x)=>s+x.c,0)/arr.length;let text='Estimación no disponible';if(Math.abs(avg)>=0.1){if(avg>0){text='Carga completa en '+fmtHours(Math.max(0,d.capacity-d.remaining)/avg)}else{text='Descarga completa en '+fmtHours(Math.max(0,d.remaining)/Math.abs(avg))}}let box=q(':scope > .eta-indicator',el);if(!box){box=document.createElement('div');box.className='eta-indicator';el.appendChild(box)}box.textContent=text+' · promedio '+windowSec+' s'})}
  function addEtaSetting(){const bodies=[q('#configBody'),q('#batteryBody')].filter(Boolean);bodies.forEach(body=>{if(q('.eta-setting',body))return;const row=document.createElement('div');row.className='option eta-setting';row.innerHTML='<span>Promedio para tiempo restante</span><select class="select etaWindow"><option value="10">10 s</option><option value="30">30 s</option><option value="60">60 s</option><option value="120">120 s</option><option value="300">5 min</option></select>';body.appendChild(row);const s=q('.etaWindow',row);s.value=String(localStorage.getItem('bs.etaWindow')||30);s.onchange=()=>localStorage.setItem('bs.etaWindow',s.value)})}

  let route=[];try{route=JSON.parse(localStorage.getItem('bs.route.points')||'[]')}catch(e){}let recording=localStorage.getItem('bs.route.recording')==='1';
  function gpsCoords(){const card=q('#cards>.card[data-id="gps"],#cards>.card[data-kind="gps"]');if(!card)return null;const txt=(card.textContent||'').replace(/,/g,'.');const nums=(txt.match(/-?\d{1,3}\.\d{3,}/g)||[]).map(Number);let lat=null,lon=null;for(const n of nums){if(lat===null&&n>=-90&&n<=90){lat=n;continue}if(lon===null&&n>=-180&&n<=180&&n!==lat){lon=n;break}}return lat===null||lon===null?null:{lat,lon}}
  function saveRoute(){localStorage.setItem('bs.route.points',JSON.stringify(route.slice(-10000)));localStorage.setItem('bs.route.recording',recording?'1':'0')}
  function ensureRoutePanel(){const card=q('#cards>.card[data-id="gps"],#cards>.card[data-kind="gps"]');if(!card)return;const body=q('.card-body',card);if(!body||q('.route-panel',body))return;const p=document.createElement('div');p.className='route-panel';p.innerHTML='<canvas class="route-map" width="640" height="640"></canvas><div class="route-state"></div><div class="route-controls"><button class="btn startRoute">Iniciar grabación</button><button class="btn stopRoute">Detener grabación</button><button class="btn exportRoute">Exportar GPX</button><button class="btn importRoute">Importar GPX</button></div>';body.appendChild(p);if(!body.style.height||body.getBoundingClientRect().height<430)body.style.height='520px';q('.startRoute',p).onclick=()=>{recording=true;saveRoute();drawRoute()};q('.stopRoute',p).onclick=()=>{recording=false;saveRoute();drawRoute()};q('.exportRoute',p).onclick=()=>{if(!window.V200Bridge)return;V200Bridge.exportGpx(toGpx())};q('.importRoute',p).onclick=()=>{if(window.V200Bridge)V200Bridge.importGpx()};drawRoute()}
  function drawRoute(){const c=q('.route-map');if(!c)return;const x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.fillStyle='#071b29';x.fillRect(0,0,w,h);x.strokeStyle='#17394f';x.lineWidth=1;for(let i=1;i<5;i++){x.beginPath();x.moveTo(i*w/5,0);x.lineTo(i*w/5,h);x.stroke();x.beginPath();x.moveTo(0,i*h/5);x.lineTo(w,i*h/5);x.stroke()}if(route.length){const lats=route.map(p=>p.lat),lons=route.map(p=>p.lon),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons),pad=35;const dx=Math.max(1e-7,maxLon-minLon),dy=Math.max(1e-7,maxLat-minLat);x.strokeStyle='#25d6e6';x.lineWidth=5;x.lineJoin='round';x.beginPath();route.forEach((p,i)=>{const px=pad+(p.lon-minLon)/dx*(w-2*pad),py=h-pad-(p.lat-minLat)/dy*(h-2*pad);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();const p=route[route.length-1],px=pad+(p.lon-minLon)/dx*(w-2*pad),py=h-pad-(p.lat-minLat)/dy*(h-2*pad);x.fillStyle='#f4f8fb';x.beginPath();x.arc(px,py,8,0,Math.PI*2);x.fill()}const st=q('.route-state');if(st){st.className='route-state'+(recording?' route-recording':'');st.textContent=(recording?'● Grabando':'Detenida')+' · '+route.length+' puntos'}}
  function recordTick(){if(!recording)return;const p=gpsCoords();if(!p)return;const last=route[route.length-1];if(last&&Math.abs(last.lat-p.lat)<1e-7&&Math.abs(last.lon-p.lon)<1e-7)return;route.push({lat:p.lat,lon:p.lon,t:Date.now()});saveRoute();drawRoute()}
  function escXml(s){return String(s).replace(/[<>&"']/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot',"'":'&apos;'}[m]))}
  function toGpx(){return '<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Boat Station '+VERSION+'" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>Boat Station Route</name><trkseg>'+route.map(p=>'<trkpt lat="'+p.lat+'" lon="'+p.lon+'"><time>'+new Date(p.t||Date.now()).toISOString()+'</time></trkpt>').join('')+'</trkseg></trk></gpx>'}
  function importGpx(raw){const pts=[];const re=/<trkpt[^>]*lat=["']([^"']+)["'][^>]*lon=["']([^"']+)["'][^>]*>([\s\S]*?)<\/trkpt>|<trkpt[^>]*lat=["']([^"']+)["'][^>]*lon=["']([^"']+)["'][^>]*\/>/gi;let m;while((m=re.exec(raw))){const lat=Number(m[1]||m[4]),lon=Number(m[2]||m[5]);if(isFinite(lat)&&isFinite(lon))pts.push({lat,lon,t:Date.now()})}if(pts.length){route=pts;recording=false;saveRoute();drawRoute();alert('Ruta importada: '+pts.length+' puntos')}else alert('No se encontraron puntos GPX')}

  function overrideBackup(){const b=q('#exportZip');if(b&&window.V200Bridge)b.onclick=()=>{const raw=window.StorageBridge?StorageBridge.loadBackup():'';V200Bridge.exportZip(raw||'')}}
  function overrideQr(){const btn=q('#showQrBtn'),sheet=q('#pairingSheet');if(!btn||!sheet||!window.V200Bridge)return;btn.onclick=()=>{let ids=[];try{ids=JSON.parse(localStorage.getItem('bs.order')||'[]')}catch(e){}const names={gps:'GPS',phone:'Estado del teléfono',seastate:'Sea State',compass:'Brújula'};const mods=ids.map(id=>names[id]||(String(id).startsWith('bank-')?'Banco de baterías':id));let stationId=localStorage.getItem('bs.stationId'),token=localStorage.getItem('bs.pairingToken');if(!stationId){stationId='bs-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem('bs.stationId',stationId)}if(!token){token=Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2);localStorage.setItem('bs.pairingToken',token)}const payload=JSON.stringify({type:'boat-station-pair',version:VERSION,stationId,token,boatName:localStorage.getItem('bs.boatName')||localStorage.getItem('boatName')||'Boat Station',modules:mods});q('#pairingRaw').textContent=payload;q('#pairingQr').src=V200Bridge.qrDataUrl(payload);q('#menuSheet').classList.remove('open');sheet.classList.add('open')}}

  window.BoatStationV200={onGpxImported:importGpx,onZipExported:ok=>{if(ok)alert('ZIP exportado correctamente')}};
  function refresh(){setVersion();ensureLatestApkLink();arrangeGps();decorateCharts();ensureRoutePanel();addEtaSetting();overrideBackup();overrideQr()}
  refresh();setInterval(()=>{refresh();etaTick();recordTick()},1000);const root=q('#cards');if(root)new MutationObserver(refresh).observe(root,{childList:true,subtree:true});
})();
