(function(){
  function q(s,r){return (r||document).querySelector(s)}
  function qa(s,r){return Array.from((r||document).querySelectorAll(s))}
  function addStyle(){var st=document.createElement('style');st.id='bs-v105-style';st.textContent=`
    :root{--accent:#25d6e6;--panel:#0b2639;--panel2:#0d2c42;--line:#1d4057;--muted:#8ea5b6;--danger:#ff6672}
    .sheet-inner{background:linear-gradient(180deg,#0c2940 0%,#092236 100%)!important;border-color:#20455c!important;border-radius:28px 28px 0 0!important;padding:18px 18px 30px!important}
    .sheet-inner h3{font-size:21px!important;letter-spacing:-.2px!important;margin:6px 0 22px!important}.handle{width:48px!important;height:5px!important;background:#3b6077!important}
    .option{padding:15px 2px!important;border-bottom:1px solid #173a50!important;gap:12px!important}.field,.select{background:#071a29!important;border:1px solid #2a5972!important;border-radius:14px!important;padding:11px 13px!important}
    .btn{background:#0b2639!important;border:1px solid #2f6682!important;border-radius:14px!important;color:#e8f4f9!important;padding:11px 15px!important;font-weight:600!important;min-height:44px!important}
    .btn:hover,.btn:active{background:#10344a!important;border-color:var(--accent)!important}.btn.action-accent{border-color:#35b9cc!important;color:#91e5ef!important;background:#0a293b!important}.btn.action-accent:before{content:'⚙';font-size:18px;margin-right:8px;color:var(--accent)}
    .btn.action-add{border-color:#35b9cc!important;color:#91e5ef!important}.btn.action-add:before{content:'＋';font-size:20px;margin-right:7px;color:var(--accent)}
    .btn.action-save{border-color:#35b9cc!important;color:#a9deea!important}.btn.action-save:before{content:'▣';font-size:18px;margin-right:8px;color:#77cfdf}
    .btn.action-danger{border-color:#ef5b6a!important;color:#ff7781!important;background:#122735!important}.btn.action-danger:before{content:'⌫';font-size:18px;margin-right:8px}
    .battery-card{background:#081c2b!important;border:1px solid #1b4058!important;border-radius:18px!important;padding:16px!important;margin:12px 0!important}.battery-top{gap:10px!important}.battery-top .name{font-size:18px!important;font-weight:800!important}.battery-card .status.ok{color:#b4df67!important}.battery-card .bankline{font-size:13px!important;margin-top:7px!important;color:#8ea5b6!important}
    .card{position:relative!important}.card.edit-selected{outline:2px solid var(--accent)!important;box-shadow:0 0 0 3px #25d6e625!important}.card.edit-selected .card-head{background:#10354b!important}
    .card.edit-selected.reordering{opacity:.94!important;box-shadow:0 8px 28px #0008,0 0 0 3px #25d6e640!important;z-index:60!important}.card.edit-selected .card-head{touch-action:none!important;cursor:grab!important}.card.edit-selected.reordering .card-head{cursor:grabbing!important}
    .card-body{transition:none!important}.resize-grip{display:none!important;position:absolute!important;left:0!important;right:0!important;bottom:0!important;height:52px!important;margin:0!important;border:0!important;opacity:1!important;align-items:flex-end!important;justify-content:center!important;padding-bottom:5px!important;background:linear-gradient(to bottom,transparent,#0b2335f2)!important;z-index:30!important;touch-action:none!important;cursor:ns-resize!important}
    .card.edit-selected .resize-grip{display:flex!important}.card.edit-selected .resize-grip:after{content:'↕';font-size:26px;font-weight:800;color:var(--accent);line-height:1}.card.edit-selected .card-body{padding-bottom:28px!important}
    .danger{color:var(--danger)!important}.backup-status{border-color:#1b4058!important;background:#081c2b!important;border-radius:16px!important}
    .qr-wrap{text-align:center}.qr-card{display:inline-block;background:#fff;border-radius:18px;padding:16px;margin:8px auto 16px}.qr-card img{display:block;width:260px;height:260px}.qr-fallback{word-break:break-all;font-size:11px;color:#9fb4c2;margin-top:10px}
  `;document.head.appendChild(st)}
  function version(){qa('#menuSheet .option').forEach(function(r){if((r.textContent||'').trim().indexOf('Versión')===0){var sm=q('small',r);if(sm)sm.textContent='0.1.5'}})}
  function decorateButtons(){qa('.btn').forEach(function(b){var t=(b.textContent||'').trim().toLowerCase();b.classList.remove('action-accent','action-add','action-save','action-danger');if(t==='configurar')b.classList.add('action-accent');else if(t.indexOf('batería')>=0&&t.indexOf('guardar')<0)b.classList.add('action-add');else if(t.indexOf('guardar')===0)b.classList.add('action-save');else if(t.indexOf('eliminar')===0)b.classList.add('action-danger')})}
  function editAndReorder(){
    var pressTimer=null,pressCard=null,pressX=0,pressY=0,drag=null,dragHead=null,startY=0,moved=false,suppressUntil=0;
    function select(card){qa('.card.edit-selected').forEach(function(c){if(c!==card)c.classList.remove('edit-selected')});card.classList.add('edit-selected')}
    function saveOrder(){var ids=qa('#cards>.card').map(function(c){return c.getAttribute('data-id')||c.dataset.id}).filter(Boolean);if(ids.length)localStorage.setItem('bs.order',JSON.stringify(ids))}
    document.addEventListener('pointerdown',function(e){var card=e.target.closest&&e.target.closest('.card');if(!card)return;var grip=e.target.closest&&e.target.closest('.resize-grip');if(grip)return;var head=e.target.closest&&e.target.closest('.card-head');if(card.classList.contains('edit-selected')&&head){drag=card;dragHead=head;startY=e.clientY;moved=false;try{head.setPointerCapture(e.pointerId)}catch(x){};return}if(e.target.closest&&e.target.closest('button,input,select,.more'))return;clearTimeout(pressTimer);pressCard=card;pressX=e.clientX;pressY=e.clientY;pressTimer=setTimeout(function(){if(pressCard){select(pressCard);if(navigator.vibrate)try{navigator.vibrate(18)}catch(x){}pressCard=null}},420)},true)
    document.addEventListener('pointermove',function(e){if(pressCard&&Math.hypot(e.clientX-pressX,e.clientY-pressY)>9){clearTimeout(pressTimer);pressCard=null}if(!drag)return;var dy=e.clientY-startY;if(!moved&&Math.abs(dy)<5)return;moved=true;e.preventDefault();e.stopImmediatePropagation();drag.classList.add('reordering');var siblings=qa('#cards>.card').filter(function(c){return c!==drag});var target=null;for(var i=0;i<siblings.length;i++){var r=siblings[i].getBoundingClientRect();if(e.clientY<r.top+r.height/2){target=siblings[i];break}}if(target){if(drag.nextElementSibling!==target)target.parentNode.insertBefore(drag,target)}else{var root=q('#cards');if(root&&root.lastElementChild!==drag)root.appendChild(drag)}},true)
    function end(e){clearTimeout(pressTimer);pressTimer=null;pressCard=null;if(!drag)return;if(moved){e.preventDefault();e.stopImmediatePropagation();drag.classList.remove('reordering');saveOrder();suppressUntil=Date.now()+350}drag=null;dragHead=null;moved=false}document.addEventListener('pointerup',end,true);document.addEventListener('pointercancel',end,true);document.addEventListener('click',function(e){if(Date.now()<suppressUntil){e.preventDefault();e.stopImmediatePropagation()}},true)
  }
  function stopCollapsedFlip(){var sx=0,sy=0,card=null;document.addEventListener('touchstart',function(e){if(e.touches.length!==1)return;card=e.target.closest&&e.target.closest('.card.collapsed');if(card){sx=e.touches[0].clientX;sy=e.touches[0].clientY}},true);document.addEventListener('touchend',function(e){if(!card||!e.changedTouches.length)return;var dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)>35&&Math.abs(dx)>Math.abs(dy)*1.15){e.stopImmediatePropagation();e.preventDefault()}card=null},true)}
  function fastResize(){var dragging=null,startY=0,startH=0,body=null,raf=0,pendingH=0;function paint(){raf=0;if(body)body.style.height=Math.round(pendingH)+'px'}document.addEventListener('pointerdown',function(e){var grip=e.target.closest&&e.target.closest('.resize-grip');if(!grip)return;var card=grip.closest('.card');body=q('.card-body',card);if(!card||!body)return;e.preventDefault();e.stopImmediatePropagation();dragging=card;startY=e.clientY;startH=body.getBoundingClientRect().height;body.style.transition='none';try{grip.setPointerCapture(e.pointerId)}catch(x){}},true);document.addEventListener('pointermove',function(e){if(!dragging||!body)return;e.preventDefault();e.stopImmediatePropagation();pendingH=Math.max(72,startH+(e.clientY-startY));if(!raf)raf=requestAnimationFrame(paint)},true);document.addEventListener('pointerup',function(e){if(!dragging||!body)return;e.preventDefault();e.stopImmediatePropagation();if(raf){cancelAnimationFrame(raf);raf=0;paint()}var id=dragging.getAttribute('data-id')||dragging.dataset.id;if(id){var h={};try{h=JSON.parse(localStorage.getItem('bs.heights')||'{}')}catch(x){}h[id]=Math.round(body.getBoundingClientRect().height);localStorage.setItem('bs.heights',JSON.stringify(h))}dragging=null;body=null},true)}
  function ensureBluetoothSheet(){if(q('#bluetoothSheet'))return;var s=document.createElement('div');s.className='sheet';s.id='bluetoothSheet';s.innerHTML='<div class="sheet-inner"><div class="handle"></div><div class="subsheet-head"><button class="btn" id="bluetoothBack">‹</button><h3 style="margin:0">Seleccionar batería Bluetooth</h3></div><div class="sub">Baterías y dispositivos BLE detectados</div><div id="bluetoothList"></div></div>';document.body.appendChild(s);q('#bluetoothBack').onclick=function(){s.classList.remove('open');q('#batterySheet').classList.add('open')};s.onclick=function(e){if(e.target===s){s.classList.remove('open');q('#batterySheet').classList.add('open')}}}
  function hookBattery(){ensureBluetoothSheet();var bs=q('#batterySheet'),origArea=q('#batteryScanArea'),list=q('#bluetoothList');if(!bs||!origArea||!list)return;function hookButton(){var b=q('#scanBattery');if(!b||b.dataset.v105)return;b.dataset.v105='1';var original=b.onclick;b.onclick=function(e){if(original)original.call(this,e);setTimeout(function(){bs.classList.remove('open');q('#bluetoothSheet').classList.add('open');mirror()},20)}}function mirror(){list.innerHTML=origArea.innerHTML||'<div class="sub">Buscando dispositivos BLE…</div>';qa('[data-pick]',list).forEach(function(btn){btn.textContent='Seleccionar';btn.onclick=function(){var a=btn.getAttribute('data-pick');var src=q('#batteryScanArea [data-pick="'+CSS.escape(a)+'"]');if(src)src.click();q('#bluetoothSheet').classList.remove('open');bs.classList.add('open')}});decorateButtons()}new MutationObserver(function(){hookButton();decorateButtons()}).observe(q('#batteryBody'),{childList:true,subtree:true});new MutationObserver(mirror).observe(origArea,{childList:true,subtree:true});hookButton()}
  function backupMenu(){var ch=q('#changeFolder');if(ch){var row=ch.closest('.option');if(row)row.remove()}var r=q('#restoreBackup');if(r)r.textContent='Restaurar';var container=q('#backupNow')&&q('#backupNow').closest('.option');if(!container||q('#exportZip'))return;var row=document.createElement('div');row.className='option';row.innerHTML='<button class="btn" id="exportZip">Exportar ZIP</button><button class="btn" id="importZip">Importar ZIP</button>';container.after(row);q('#exportZip').onclick=function(){if(!window.StorageBridge)return;var bn=q('#backupNow');if(bn)bn.click();setTimeout(function(){var raw=StorageBridge.loadBackup();StorageBridge.exportZip(raw||'')},100)};q('#importZip').onclick=function(){if(window.StorageBridge)StorageBridge.importZip()}}
  function pairingQR(){
    if(q('#pairingSheet'))return;
    var menu=q('#menuSheet .sheet-inner');if(!menu)return;
    var row=document.createElement('div');row.className='option';row.innerHTML='<span>Boat Station Remote</span><button class="btn" id="showQrBtn">Mostrar QR</button>';menu.appendChild(row);
    var s=document.createElement('div');s.className='sheet';s.id='pairingSheet';s.innerHTML='<div class="sheet-inner"><div class="handle"></div><div class="subsheet-head"><button class="btn" id="pairingBack">‹</button><h3 style="margin:0">Vincular Boat Station Remote</h3></div><div class="qr-wrap"><div class="sub" style="margin-bottom:10px">Escaneá este código desde Boat Station Remote.</div><div class="qr-card"><img id="pairingQr" alt="QR de vinculación"></div><div class="qr-fallback" id="pairingRaw"></div></div></div>';document.body.appendChild(s);
    function rnd(){try{return crypto.randomUUID()}catch(e){return 'bs-'+Date.now()+'-'+Math.random().toString(36).slice(2)}}
    function getStored(k){var v=localStorage.getItem(k);if(!v){v=rnd();localStorage.setItem(k,v)}return v}
    q('#showQrBtn').onclick=function(){
      var stationId=getStored('bs.stationId'),token=getStored('bs.pairingToken'),boatName=localStorage.getItem('bs.boatName')||localStorage.getItem('boatName')||'Boat Station';var ids=[];try{ids=JSON.parse(localStorage.getItem('bs.order')||'[]')}catch(e){}var names={gps:'GPS',phone:'Estado del teléfono',seastate:'Sea State',compass:'Brújula'};var mods=ids.map(function(id){if(names[id])return names[id];if(String(id).indexOf('bank-')===0)return 'Banco de baterías';return id});var payload=JSON.stringify({type:'boat-station-pair',version:'0.1.5',stationId:stationId,token:token,boatName:boatName,modules:mods});q('#pairingRaw').textContent=payload;q('#pairingQr').src='https://api.qrserver.com/v1/create-qr-code/?size=520x520&margin=12&data='+encodeURIComponent(payload);q('#menuSheet').classList.remove('open');s.classList.add('open')
    };
    q('#pairingBack').onclick=function(){s.classList.remove('open');q('#menuSheet').classList.add('open')};s.onclick=function(e){if(e.target===s)s.classList.remove('open')}
  }
  addStyle();version();stopCollapsedFlip();fastResize();editAndReorder();ensureBluetoothSheet();hookBattery();backupMenu();pairingQR();decorateButtons();
  var root=q('#cards');if(root)new MutationObserver(function(){hookBattery();decorateButtons()}).observe(root,{childList:true,subtree:true});var cfg=q('#configBody');if(cfg)new MutationObserver(decorateButtons).observe(cfg,{childList:true,subtree:true});
})();
