(function(){
  const params=new URLSearchParams(location.search);
  const isLocal=params.get('mode')==='station'||!!window.CoreBridge||!!window.BoatStationCore||!!window.NativeBridge;
  if(isLocal)return;
  const q=(s,r)=>(r||document).querySelector(s);
  let clientId=localStorage.getItem('bs.remote.clientId');if(!clientId){clientId='web-'+Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem('bs.remote.clientId',clientId)}
  let lastOk=0,lastStation='';
  function backend(){return String(window.BOAT_STATION_BACKEND||'').replace(/\/$/,'')}
  function active(){return window.BoatStationStations&&BoatStationStations.active?BoatStationStations.active():null}
  function clientName(){return window.BoatStationStations&&BoatStationStations.stationName?BoatStationStations.stationName():(localStorage.getItem('bs.stationName')||'Estación')}
  function status(){const inner=q('#menuSheet .sheet-inner');if(!inner)return;let row=q('#remoteConnectionStatus',inner);if(!row){row=document.createElement('div');row.className='option';row.id='remoteConnectionStatus';row.innerHTML='<span>Conexión remota<br><small class="sub" id="remoteConnectionText">Sin estación activa</small></span><span class="status" id="remoteConnectionAge"></span>';inner.appendChild(row)}const t=q('#remoteConnectionText'),a=q('#remoteConnectionAge');const p=active();if(!p){t.textContent='Sin estación activa';a.textContent='';return}const age=lastOk?Math.round((Date.now()-lastOk)/1000):null;t.textContent=lastStation?'Conectado a '+lastStation:'Esperando datos de '+(p.name||'Boat Station');a.textContent=age==null?'':(age<5?'Ahora':age+' s');a.className='status'+(age!=null&&age<15?' ok':'')}
  function apply(data,p){const snap=data&&data.snapshot||{};lastOk=Date.now();lastStation=data.boatName||snap.boatName||p.name||'Boat Station';const a=window.BoatStationStations&&BoatStationStations.readStations?BoatStationStations.readStations():[];const row=a.find(x=>x.stationId===p.stationId);if(row){row.name=lastStation;row.lastSeen=lastOk;localStorage.setItem('bs.remote.stations',JSON.stringify(a))}if(snap.cardsHtml){const cards=q('#cards');if(cards)cards.innerHTML=snap.cardsHtml}document.body.dataset.remoteMode='1';status()}
  async function poll(){const p=active(),b=backend();if(!p||!b){status();return}try{const u=b+'/api/station/'+encodeURIComponent(p.stationId)+'/state?clientId='+encodeURIComponent(clientId)+'&clientName='+encodeURIComponent(clientName());const r=await fetch(u,{headers:{Authorization:'Bearer '+p.token},cache:'no-store'});if(!r.ok)throw 0;apply(await r.json(),p)}catch(e){status()}}
  window.addEventListener('boatstation-remote-paired',()=>{lastOk=0;lastStation='';poll()});window.addEventListener('boatstation-active-station-changed',()=>{lastOk=0;lastStation='';poll()});poll();setInterval(poll,2000);setInterval(status,1000);
})();