const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const params=new URLSearchParams(location.search);
const isLocal=params.get('mode')==='station'||!!window.CoreBridge||!!window.BoatStationCore||!!window.NativeBridge;
const backend='https://boat-station-backend.ezequielpanza.workers.dev';
const norm=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,16);
const pretty=v=>(norm(v).match(/.{1,4}/g)||[]).join('-');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));

function defaultName(){let n=localStorage.getItem('bs.stationName');if(n)return n;try{const m=(navigator.userAgent||'').match(/Android[^;]*;\s*([^;)]+?)(?:\s+Build\/|;|\))/i);if(m)n=m[1].trim()}catch{}if(!n)try{n=navigator.userAgentData?.platform||navigator.platform||''}catch{}if(!n||/^(Linux|Android|Win32|MacIntel|iPhone|iPad)$/i.test(n))n='Estación';localStorage.setItem('bs.stationName',n);return n}
function name(){return localStorage.getItem('bs.stationName')||defaultName()}
function identity(){let code=norm(localStorage.getItem('bs.stationCode'));if(code.length!==16){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';code='';for(let i=0;i<16;i++)code+=chars[Math.floor(Math.random()*chars.length)];localStorage.setItem('bs.stationCode',code)}const stationId='bs-'+code,token='pc-'+code;localStorage.setItem('bs.stationId',stationId);localStorage.setItem('bs.pairingToken',token);return{stationId,token,code}}
function stations(){try{const a=JSON.parse(localStorage.getItem('bs.remote.stations')||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function saveStations(a){localStorage.setItem('bs.remote.stations',JSON.stringify(a))}
function active(){const a=stations(),id=localStorage.getItem('bs.remote.activeStation');return a.find(x=>x.stationId===id)||a[0]||null}
function addPair(data){if(typeof data==='string'){const t=data.trim();try{data=t.startsWith('{')?JSON.parse(t):{manualCode:norm(t)}}catch{data={manualCode:norm(t)}}}data=data||{};const code=norm(data.manualCode);if(code.length===16&&!data.stationId){data.stationId='bs-'+code;data.token='pc-'+code}if(!data.stationId||!data.token)throw new Error('Código inválido');const a=stations().filter(x=>x.stationId!==data.stationId);const row={stationId:data.stationId,token:data.token,name:data.stationName||data.boatName||'Estación'};a.push(row);saveStations(a);localStorage.setItem('bs.remote.activeStation',row.stationId);return row}

async function fetchTimed(url,options={},timeoutMs=7000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}

const panel=document.createElement('div');panel.id='stationManager';panel.className='station-manager';panel.innerHTML='<div class="sm-head"><button class="sm-back" id="smBack">‹</button><h2>Gestión de Estaciones</h2></div><div id="smBody"></div>';document.body.appendChild(panel);
let stream=null;
async function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=$('#smVideo');if(v){v.srcObject=null;v.classList.remove('open')}}
$('#smBack').onclick=()=>{panel.classList.remove('open');stopCamera()};

function ensureMenu(){const inner=$('#menuSheet .sheet-inner');if(!inner||$('#stationManagerRow',inner))return;const row=document.createElement('div');row.className='option';row.id='stationManagerRow';row.innerHTML='<span>Gestión de Estaciones<br><small class="sub">'+(isLocal?'Esta estación: '+esc(name()):(active()?'Activa: '+esc(active().name):'Sin vincular'))+'</small></span>';inner.appendChild(row);row.onclick=()=>{panel.classList.add('open');$('#menuSheet')?.classList.remove('open');render()}}

async function scan(){const st=$('#smStatus'),v=$('#smVideo');if(!navigator.mediaDevices?.getUserMedia){st.textContent='Cámara no disponible';return}if(!('BarcodeDetector'in window)){st.textContent='Este navegador no admite QR directo. Usá el código.';return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});v.srcObject=stream;v.classList.add('open');await v.play();const detector=new BarcodeDetector({formats:['qr_code']});(async function loop(){if(!stream)return;try{const codes=await detector.detect(v);if(codes?.length){addPair(codes[0].rawValue);await stopCamera();render();return}}catch{}requestAnimationFrame(loop)})()}catch{st.textContent='No se pudo abrir la cámara'}}

function render(){const b=$('#smBody');if(isLocal){const id=identity();const payload=JSON.stringify({type:'boat-station-pair',stationId:id.stationId,token:id.token,manualCode:id.code,stationName:name(),boatName:name()});b.innerHTML='<div class="sm-card"><div class="sm-label">Nombre de la estación</div><input id="smName" class="sm-input" value="'+esc(name())+'"></div><div class="sm-card"><div class="sm-label">Vincular a esta estación</div><div class="sm-code">'+pretty(id.code)+'</div><img id="smQr" class="sm-qr" alt="QR de vinculación"><div class="sm-actions"><button id="smQrBtn" class="sm-btn">Mostrar QR</button><button id="smCopy" class="sm-btn">Copiar código</button></div></div><div class="sm-card"><div class="sm-label">Clientes conectados</div><div id="smClients" class="sm-sub">Consultando…</div></div>';$('#smName').onchange=e=>{localStorage.setItem('bs.stationName',e.target.value.trim()||'Estación');render()};const show=()=>{const img=$('#smQr');const src=window.BoatStationTools?.qrDataUrl?.(payload);if(src)img.src=src;else img.style.display='none'};show();$('#smQrBtn').onclick=show;$('#smCopy').onclick=async()=>{try{await navigator.clipboard.writeText(pretty(id.code));$('#smCopy').textContent='Copiado'}catch{}};loadClients();return}
 const a=stations(),act=active();const rows=a.map(x=>'<div class="sm-row"><div class="sm-main"><div class="sm-name">'+esc(x.name)+'</div><div class="sm-sub">'+esc(x.stationId)+(act?.stationId===x.stationId?' · <span class="sm-active">ACTIVA</span>':'')+'</div></div><button class="sm-btn" data-active="'+esc(x.stationId)+'">'+(act?.stationId===x.stationId?'Activa':'Elegir')+'</button><button class="sm-btn" data-remove="'+esc(x.stationId)+'">×</button></div>').join('');b.innerHTML='<div class="sm-card"><div class="sm-label">Nombre de este cliente</div><input id="smName" class="sm-input" value="'+esc(name())+'"></div><div class="sm-card"><div class="sm-label">Conectar a una estación</div><div class="sm-actions"><button id="smScan" class="sm-btn">Escanear QR</button><button id="smManualToggle" class="sm-btn">Ingresar código</button></div><div id="smManual" style="display:none;margin-top:10px"><input id="smCode" class="sm-input" maxlength="19" placeholder="XXXX-XXXX-XXXX-XXXX"><button id="smConnect" class="sm-btn" style="width:100%;margin-top:8px">Vincular</button></div><video id="smVideo" class="sm-video" playsinline></video><div id="smStatus" class="sm-status"></div></div><div class="sm-card"><div class="sm-label">Estaciones vinculadas</div>'+(rows||'<div class="sm-sub">No hay estaciones vinculadas</div>')+'</div>';$('#smName').onchange=e=>{localStorage.setItem('bs.stationName',e.target.value.trim()||'Estación');render()};$('#smScan').onclick=scan;$('#smManualToggle').onclick=()=>$('#smManual').style.display=$('#smManual').style.display==='none'?'block':'none';$('#smCode').oninput=e=>e.target.value=pretty(e.target.value);$('#smConnect').onclick=()=>{try{addPair({manualCode:norm($('#smCode').value)});render();requestImmediateSync()}catch(e){$('#smStatus').textContent=e.message}};$$('[data-active]',b).forEach(x=>x.onclick=()=>{localStorage.setItem('bs.remote.activeStation',x.dataset.active);render();requestImmediateSync()});$$('[data-remove]',b).forEach(x=>x.onclick=()=>{const out=stations().filter(s=>s.stationId!==x.dataset.remove);saveStations(out);if(localStorage.getItem('bs.remote.activeStation')===x.dataset.remove)localStorage.setItem('bs.remote.activeStation',out[0]?.stationId||'');render();requestImmediateSync()})}

async function loadClients(){const w=$('#smClients');if(!w)return;const id=identity();try{const r=await fetchTimed(`${backend}/api/station/${encodeURIComponent(id.stationId)}/clients`,{headers:{Authorization:'Bearer '+id.token},cache:'no-store'});const d=await r.json();w.innerHTML=d.clients?.length?d.clients.map((c,i)=>'<div class="sm-row"><div class="sm-main"><div class="sm-name">'+esc(c.name||('Cliente '+(i+1)))+'</div><div class="sm-sub">Conectado ahora</div></div></div>').join(''):'Ningún cliente conectado ahora'}catch{w.textContent='Sin conexión con el servidor'}}

let syncTimer=0,syncRunning=false,syncRequested=false,stopped=false;
async function publishOnce(){const id=identity(),cards=$('#cards');await fetchTimed(`${backend}/api/station/${encodeURIComponent(id.stationId)}/state`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:id.token,boatName:name(),snapshot:{cardsHtml:cards?.innerHTML||'',boatName:name()}})},7000)}
async function pollOnce(){const a=active();if(!a)return;let clientId=localStorage.getItem('bs.remote.clientId');if(!clientId){clientId='web-'+Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem('bs.remote.clientId',clientId)}const r=await fetchTimed(`${backend}/api/station/${encodeURIComponent(a.stationId)}/state?clientId=${encodeURIComponent(clientId)}&clientName=${encodeURIComponent(name())}`,{headers:{Authorization:'Bearer '+a.token},cache:'no-store'},7000);if(!r.ok)return;const d=await r.json();if(d.snapshot?.cardsHtml){const html=d.snapshot.cardsHtml;if(window.BoatStationRemoteUI?.applySnapshot)window.BoatStationRemoteUI.applySnapshot(html);else{const c=$('#cards');if(c)c.innerHTML=html}document.documentElement.classList.remove('bs-remote');$('#remoteLanding')?.remove()}}
async function syncCycle(){if(stopped||syncRunning)return;syncRunning=true;try{if(isLocal)await publishOnce();else await pollOnce()}catch(e){if(e?.name!=='AbortError')console.warn('Boat Station sync',e)}finally{syncRunning=false;const delay=syncRequested?100:2000;syncRequested=false;if(!stopped)syncTimer=setTimeout(syncCycle,delay)}}
function requestImmediateSync(){syncRequested=true;if(!syncRunning){clearTimeout(syncTimer);syncTimer=setTimeout(syncCycle,0)}}
function stopSync(){stopped=true;clearTimeout(syncTimer)}

ensureMenu();new MutationObserver(ensureMenu).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden)return;requestImmediateSync()});
window.addEventListener('pagehide',stopSync,{once:true});
syncCycle();
